version: 2
updates:
- package-ecosystem: pip
  directory: "/base"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.4.9
  - dependency-name: pytest-xdist
    versions:
    - 2.2.0
  - dependency-name: tornado
    versions:
    - "6.1"
- package-ecosystem: docker
  directory: "/base"
  schedule:
    interval: daily
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.1
