#!/bin/sh

# Tell nginx the address of the backend service to proxy to
sed -i "s/{{TARGET_SERVICE}}/${TARGET_SERVICE:-localhost}/g;" /etc/nginx/nginx.conf
sleep 2
echo "[INFO]  Starting web server"
echo "[INFO]  Backend: $TARGET_SERVICE"
exec nginx -g "daemon off;"
