apiVersion: batch/v1
kind: Job
metadata:
  name: anonlinkintegrationtest
  labels:
    jobgroup: integration-test
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        jobgroup: integration-test
    spec:
      restartPolicy: Never
      containers:
      - name: entitytester
        image: quay.io/n1analytics/entity-app
        imagePullPolicy: Always
        env:
          - name: ENTITY_SERVICE_URL
            value: https://beta.anonlink.data61.xyz/api/v1
          - name: LOGGING_LEVEL
            value: "INFO"
        command:
          - "python"
          - "-m"
          - "pytest"
          - "entityservice/tests"
          - "-x"
      imagePullSecrets:
      - name: n1-quay-pull-secret
