kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: entityservice-benchmark-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: default
