apiVersion: batch/v1
kind: Job
metadata:
  name: entityservice-testing-bench
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: entityservice
        tier: aux
    spec:
      restartPolicy: Never
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /cache"]
        volumeMounts:
        - name: data-volume
          mountPath: /cache
      containers:
      - name: entitytester
        image: quay.io/n1analytics/entity-benchmark:v0.2.0
        env:
          - name: SERVER
            value: "https://testing.es.data61.xyz"
          - name: TIMEOUT
            value: "1200"
          - name: EXPERIMENT
            value: "/config/experiments.json"
          - name: DATA_PATH
            value: "/cache"
          - name: SCHEMA
            value: "/cache/schema.json"
          - name: RESULTS_PATH
            value: "/app/results.json"
        volumeMounts:
          - name: experiments-volume
            mountPath: /config
          - name: data-volume
            mountPath: /cache
      volumes:
        - name: experiments-volume
          configMap:
            name: entityservice-benchmark-experiments
        - name: data-volume
          persistentVolumeClaim:
            claimName: entityservice-benchmark-data
