apiVersion: v1
kind: Service
metadata:
{{- if .Values.api.service.annotations }}
  annotations:
{{ toYaml .Values.api.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "es.release_labels" . | indent 4 }}
    component: "{{ .Values.api.name }}"
{{- if .Values.api.service.labels }}
{{ toYaml .Values.api.service.labels | indent 4 }}
{{- end }}
  name: {{ template "api.fullname" . }}
spec:
{{- if .Values.api.service.clusterIp }}
  clusterIP: {{ .Values.api.service.clusterIp }}
{{- end }}
{{- if .Values.api.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.api.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - name: http
      port: {{ required "api.service.servicePort must be provided." .Values.api.service.servicePort }}
      protocol: TCP
      targetPort: "entity-nginx"
  selector:
    app: {{ template "es.appname" . }}
    component: {{ required "api.name must be provided." .Values.api.name | quote }}
    release: {{ .Release.Name }}
  type: {{ required "api.service.type must be provided." .Values.api.service.type }}
