apiVersion: v1
kind: Secret
metadata:
  name: {{ template "es.fullname" . }}
  labels: {{ include "es.release_labels" . | nindent 4 }}
data:
  DATABASE_PASSWORD: {{ required "global.postgresql.postgresqlPassword must be provided." .Values.global.postgresql.postgresqlPassword | b64enc | quote }}
  REDIS_PASSWORD: {{ required "redis.password must be provided." .Values.redis.password | b64enc | quote }}
  MINIO_ACCESS_KEY: {{ required "minio.accessKey must be provided." .Values.minio.accessKey | b64enc | quote }}
  MINIO_SECRET_KEY: {{ required "minio.secretKey must be provided." .Values.minio.secretKey | b64enc | quote }}
  UPLOAD_OBJECT_STORE_ACCESS_KEY: {{ required "anonlink.objectstore.uploadAccessKey must be provided." .Values.anonlink.objectstore.uploadAccessKey | b64enc | quote }}
  UPLOAD_OBJECT_STORE_SECRET_KEY: {{ required "anonlink.objectstore.uploadSecretKey must be provided." .Values.anonlink.objectstore.uploadSecretKey | b64enc | quote }}
  DOWNLOAD_OBJECT_STORE_ACCESS_KEY: {{ required "anonlink.objectstore.downloadAccessKey must be provided." .Values.anonlink.objectstore.downloadAccessKey | b64enc | quote }}
  DOWNLOAD_OBJECT_STORE_SECRET_KEY: {{ required "anonlink.objectstore.downloadSecretKey must be provided." .Values.anonlink.objectstore.downloadSecretKey | b64enc | quote }}
