apiVersion: v1
kind: Secret
metadata:
  name: {{ template "es.fullname" . }}
  labels:
    {{-include "es.release_labels" . }}
data:
  postgresPassword: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  redisPassword: {{ .Values.redis.redisPassword | b64enc | quote }}
  minioAccessKey: {{ .Values.minio.accessKey | b64enc | quote }}
  minioSecretKey: {{ .Values.minio.secretKey | b64enc | quote }}
