apiVersion: v1
kind: Secret
metadata:
  name: {{ template "es.fullname" . }}
  labels:
    {{- include "es.release_labels" . | indent 4 }}
data:
  postgresPassword: {{ required "global.postgresql.postgresqlPassword must be provided." .Values.global.postgresql.postgresqlPassword | b64enc | quote }}
  redisPassword: {{ required "redis.password must be provided." .Values.redis.password | b64enc | quote }}
  minioAccessKey: {{ required "minio.accessKey must be provided." .Values.minio.accessKey | b64enc | quote }}
  minioSecretKey: {{ required "minio.secretKey must be provided." .Values.minio.secretKey | b64enc | quote }}
