apiVersion: v1
kind: Secret
metadata:
  name: {{ template "es.fullname" . }}
  labels:
    {{- include "es.release_labels" . | indent 4 }}
data:
  postgresPassword: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  redisPassword: {{ index .Values "redis" "password" | b64enc | quote }}
  minioAccessKey: {{ .Values.minio.accessKey | b64enc | quote }}
  minioSecretKey: {{ .Values.minio.secretKey | b64enc | quote }}
