{{- if .Values.api.dbinit.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "es.fullname" . }}-init-db
  labels:
    {{- include "es.release_labels" . | indent 4 }}
    tier: aux
  annotations:
    # This job only gets executed on install, not after an upgrade.
    # Manual intervention (or a job with a post-upgrade hook) is required to migrate a
    # production database.
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
spec:
  template:
    metadata:
      name: {{ template "name" . }}-init-db
      labels:
        {{- include "es.release_labels" . | indent 8 }}
    spec:
      containers:
      - name: db-init
        image: {{ .Values.api.dbinit.image.repository }}:{{ .Values.api.dbinit.image.tag }}
        resources:
{{ toYaml .Values.api.dbinit.resources | indent 10 }}
        envFrom:
          - configMapRef:
              name: {{ template "es.fullname" . }} 
        env:
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "es.fullname" . }}
                key: postgresPassword
          - name: DEBUG
            value: {{default "false" .Values.api.app.debug | quote }}
          - name: FLASK_APP
            value: entityservice
        command:
          - "python"
          - "-m"
          - "flask"
          - "initdb"
      restartPolicy: Never
      imagePullSecrets:
      - name: {{ .Values.api.pullSecret }}
{{- end }}
