{{- if .Values.workers.monitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "api.fullname" . }}-monitor
  labels:
    {{- include "es.release_labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      name: http
      targetPort: "celery-monitor"
  selector:
    {{- include "es.match_labels" . | indent 4 }}
    app.kubernetes.io/component: celery-monitor
{{- end }}
