{{- if .Values.workers.autoscaler.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: worker-auto-scale
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Release.Name }}-worker
  minReplicas: {{ required "workers.replicaCount must be provided."  .Values.workers.replicaCount }}
  maxReplicas: 20
  targetCPUUtilizationPercentage: 75
{{- end -}}
