{{- if .Values.workers.autoscaler.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    {{- include "es.release_labels" . | indent 4 }}
  name: worker-auto-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-worker
  minReplicas: {{ required "workers.autoscaler.minReplicas must be provided."  .Values.workers.autoscaler.minReplicas }}
  maxReplicas: {{ required "workers.autoscaler.maxReplicas must be provided." .Values.workers.autoscaler.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
{{- end -}}
