name: entity-service
version: 1.7.1
description: Privacy preserving entity matching
home: es.data61.xyz
sources:
  - https://github.com/n1analytics/entity-service
  - https://github.com/n1analytics/anonlink
  - https://github.com/n1analytics/clkhash

maintainers:
  - name: N1 Analytics
    email: support@n1analytics.com
icon: https://s3-us-west-2.amazonaws.com/slack-files2/avatars/2016-04-11/33560836053_df0d62a81bf32f53df00_72.png
