name: entity-service
appVersion: 1.11.2
version: 1.12.0
description: Privacy preserving record linkage service
sources:
  - https://github.com/data61/anonlink-entity-service
  - https://github.com/data61/anonlink
  - https://github.com/data61/clkhash
maintainers:
  - name: Brian Thorne
    email: brian.thorne@data61.csiro.au
    url: https://data61.csiro.au
icon: https://s3-us-west-2.amazonaws.com/slack-files2/avatars/2016-04-11/33560836053_df0d62a81bf32f53df00_72.png
