apiVersion: v2
name: entity-service
appVersion: 1.14.0
version: 1.14.1
description: Privacy preserving record linkage service
type: application
sources:
  - https://github.com/data61/anonlink-entity-service
  - https://github.com/data61/anonlink
  - https://github.com/data61/clkhash
maintainers:
  - name: Confidential Computing
    url: https://data61.csiro.au
icon: https://s3-us-west-2.amazonaws.com/slack-files2/avatars/2016-04-11/33560836053_df0d62a81bf32f53df00_72.png
dependencies:
  - name: redis-ha
    version: 4.10.5
    repository: https://dandydeveloper.github.io/charts
    condition: provision.redis
  - name: minio
    version: 8.0.10
    repository: https://helm.min.io/
    condition: provision.minio
  - name: postgresql
    version: 10.9.2
    repository: https://charts.bitnami.com/bitnami
    condition: provision.postgresql
