## https://kubernetes.io/docs/user-guide/compute-resources

api:
  app:
    resources:
      limits:
        memory: 512Mi
        cpu: 100m
      requests:
        cpu: 50m
        memory: 256Mi

workers:
  replicaCount: 1

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

postgresql:
  resources:
    limits:
      memory: 200Mi
    requests:
      memory: 100Mi
      cpu: 100m

  persistence:
    size: 1Gi

redis:
  persistence:
    size: 1Gi
  resources:
    limits:
      memory: 200Mi
    requests:
      memory: 100Mi
      cpu: 100m

minio:
  persistence:
    enabled: false
    size: 1Gi
