dependencies:
  - name: redis-ha
    version: 2.2.0
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: minio
    version: 1.3.4
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: postgresql
    version: 0.14.4
    repository: https://kubernetes-charts.storage.googleapis.com
