dependencies:
  - name: redis-ha
    version: 2.2.3
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: provision.redis
  - name: minio
    version: 1.6.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: provision.minio
  - name: postgresql
    version: 1.0.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: provision.postgresql