dependencies:
  - name: redis-ha
    version: 3.0.3
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: provision.redis
  - name: minio
    version: 1.6.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: provision.minio
  - name: postgresql
    version: 3.11.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: provision.postgresql