dependencies:
  - name: redis-ha
    version: 2.2.1
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: provision.redis
  - name: minio
    version: 1.6.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: provision.minio
  - name: postgresql
    version: 0.14.4
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: provision.postgresql