dependencies:
  - name: redis-ha
    version: 4.10.5
    repository: https://dandydeveloper.github.io/charts
    condition: provision.redis
  - name: minio
    version: 8.0.6
    repository: https://helm.min.io/
    condition: provision.minio
  - name: postgresql
    version: 8.9.1
    repository: https://charts.bitnami.com/bitnami
    condition: provision.postgresql
