dependencies:
  - name: redis
    version: 0.8.1
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: minio
    version: 1.3.3
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: postgresql
    version: 0.7.1
    repository: https://kubernetes-charts.storage.googleapis.com
