dependencies:
  - name: redis-ha
    version: 4.4.1
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: provision.redis
  - name: minio
    version: 5.0.22
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: provision.minio
  - name: postgresql
    version: 8.9.1
    repository: https://charts.bitnami.com/bitnami
    condition: provision.postgresql
