dependencies:
  - name: redis-ha
    version: 3.0.3
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: provision.redis
  - name: minio
    version: 5.0.6
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: provision.minio
  - name: postgresql
    version: 5.2.1
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: provision.postgresql