kind: StorageClass
apiVersion: storage.k8s.io/v1beta1

metadata:
  name: default
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
    kubernetes.io/description: "Dynamic provisioned AWS EBS volumes"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  encrypted: "false"


