"""drop foreign keys of encodingblocks

Revision ID: 3502b3bd8797
Revises: fc138b64c1e7
Create Date: 2021-09-15 23:50:34.606735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3502b3bd8797'
down_revision = 'fc138b64c1e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('encodingblocks_block_id_fkey', 'encodingblocks', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('encodingblocks_block_id_fkey', 'encodingblocks', 'blocks', ['block_id'], ['block_id'])
    # ### end Alembic commands ###
