"""added_dp_to_encoding

Revision ID: 9a5d78339327
Revises: e321799791b7
Create Date: 2021-08-30 14:18:10.077436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5d78339327'
down_revision = 'e321799791b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encodings', sa.Column('dp', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_encoding_dp', 'encodings', 'dataproviders', ['dp'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_encoding_dp', 'encodings', type_='foreignkey')
    op.drop_column('encodings', 'dp')
    # ### end Alembic commands ###
