"""drop fkey encodingblocks block id

Revision ID: a182daa65383
Revises: b864dd28b375
Create Date: 2021-09-20 15:54:00.877102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a182daa65383'
down_revision = 'b864dd28b375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('encodingblocks_block_id_fkey', 'encodingblocks', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('encodingblocks_block_id_fkey', 'encodingblocks', 'blocks', ['block_id'], ['block_id'])
    # ### end Alembic commands ###
