"""add indices on fkeys

Revision ID: b864dd28b375
Revises: fc138b64c1e7
Create Date: 2021-09-16 16:14:00.764732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b864dd28b375'
down_revision = 'fc138b64c1e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blocks_dp'), 'blocks', ['dp'], unique=False)
    op.alter_column('encodingblocks', 'block_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_runs_project'), 'runs', ['project'], unique=False)
    op.create_index(op.f('ix_uploads_dp'), 'uploads', ['dp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_dp'), table_name='uploads')
    op.drop_index(op.f('ix_runs_project'), table_name='runs')
    op.alter_column('encodingblocks', 'block_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_blocks_dp'), table_name='blocks')
    # ### end Alembic commands ###
