version: '2.2'
services:


  tests:
    image: quay.io/n1analytics/entity-app
    environment:
      - ENTITY_SERVICE_URL=http://nginx:8851/api/v1
      - INITIAL_DELAY=20
    entrypoint: /bin/sh -c "sleep 10; python -m pytest entityservice/tests"
    depends_on:
      - db
      - redis
      - worker
      - nginx
