version: '2'
services:

  # The integration test
  ci:
    image: quay.io/n1analytics/entity-app
    environment:
      - DEBUG=true
      - ENTITY_SERVICE_URL=http://nginx:8851/api/v1
      - ENTITY_SERVICE_TEST_SIZE=1000
      - ENTITY_SERVICE_PERMUTATION=true
      - ENTITY_SERVICE_TEST_REPEATS=1
      - INITIAL_DELAY=60
    entrypoint: python test_service.py
    depends_on:
      - db
      - redis
      - worker
      - nginx

  tests:
    image: quay.io/n1analytics/entity-app
    environment:
      - DEBUG=true
      - ENTITY_SERVICE_URL=http://nginx:8851/api/v1
    entrypoint: /bin/sh -c "sleep 10; nosetests tests"
    depends_on:
      - db
      - redis
      - worker
      - nginx

