version: '3.4'
services:


  tests:
    image: data61/anonlink-app:${TAG:-latest}
    environment:
      - SERVER=http://nginx:8851
      - INITIAL_DELAY=20
      - JAEGER_AGENT_HOST=jaeger
    command: /bin/sh -c "dockerize -wait tcp://nginx:8851/v1/status -timeout 1m python -m pytest -n 4 entityservice/tests --junitxml=testResults.xml -x"
    depends_on:
      - db
      - redis
      - worker
      - nginx

  integrationtests:
    image: data61/anonlink-app:${TAG:-latest}
    environment:
      - SERVER=http://nginx:8851
      - INITIAL_DELAY=20
      - DATABASE_PASSWORD=rX%QpV7Xgyrz
    command: /bin/sh -c "dockerize -wait tcp://nginx:8851/v1/status -timeout 1m python -m pytest -n 1 entityservice/integrationtests --junitxml=testResults.xml -x"
    depends_on:
      - db
      - backend
      - worker
      - nginx

  benchmark:
    image: data61/anonlink-benchmark:${TAG:-latest}
    environment:
      - SERVER=http://nginx:8851
      - DATA_PATH=/cache
      - EXPERIMENT=/app/linkage-bench-cache-experiments.json
      - RESULTS_PATH=/app/results.json
    depends_on:
      - db
      - redis
      - worker
      - nginx
    entrypoint: /bin/sh -c "dockerize -wait tcp://nginx:8851/v1/status -timeout 1m python benchmark.py"
    volumes:
      - benchmarkdata:/cache

  tutorials:
    image: data61/anonlink-docs-tutorials:${TAG:-latest}
    environment:
      - SERVER=http://nginx:8851
    depends_on:
      - db
      - redis
      - worker
      - nginx
    entrypoint: /bin/sh -c "dockerize -wait tcp://nginx:8851/v1/status -timeout 1m python -m pytest --junitxml=testResults.xml -x --nbval-lax /src"

volumes:
  benchmarkdata:
